apiVersion: apps/v1
kind: Deployment
metadata:
  name: oom-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oom-demo
  template:
    metadata:
      labels:
        app: oom-demo
    spec:
      containers:
      - name: oom-demo
        image: ghcr.io/eddiewebb/oom:happy
        resources:
          requests:
            memory: "50Mi" 
          limits:
            memory: "100Mi" 
